spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2b8
    username: root
    password: adminpwd
    driver-class-name: com.mysql.cj.jdbc.Driver