# 本地环境

server:
  port: 8081

spring:
  application:
    name: api-service

  # 数据源配置
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/db_springboot?serverTimezone=GMT%2b8
    username: root
    password: adminpwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 时间参数返回格式的全局配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 404 交给异常处理器处理
#spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false
