# 本地环境

server:
  port: 8081

spring:
  application:
    name: api-service
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  # 数据源配置(使用unicode编码；字符集为UTF-8；防止0000-00-00...等异常日期参数值的异常，转为null处理；不适用SSL连接；防止MyBatis Generator 生成器把其他数据库的同名表生成下来的问题；设置时区为GMT+8)
  datasource:
    #    url: jdbc:mysql://192.168.1.104:3306/db_springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2b8
    url: jdbc:mysql://192.168.182.129:3306/db_springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2b8
    username: root
    password: adminpwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 时间参数返回格式的全局配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
