# 本地环境
server:
  port: 8081

spring:
  application:
    name: api-service
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  # 数据源配置(使用unicode编码；字符集为UTF-8；防止0000-00-00...等异常日期参数值的异常，转为null处理；不适用SSL连接；防止MyBatis Generator 生成器把其他数据库的同名表生成下来的问题；设置时区为GMT+8)
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2b8
    username: root
    password: adminpwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis 配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    # lettuce连接池配置
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

  # 时间参数返回格式的全局配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 日志文件配置
logging:
  config: classpath:logback-spring.xml

# 控制台打印mybatis语句日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# okhttp配置
springboot:
  okhttp:
    connectTimeout: 60000
    readTimeout: 60000
    writeTimeout: 60000
    maxIdleConnections: 30
    keepAliveDuration: 5
    logLevel: BODY

# 生产环境设置为false，其他环境设置为true
swagger:
  api:
    enable: true
  base-package: com.rocky.boot.api.web.controller