spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.86:3306/spring_boot_security
    username: root
    password:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: INFO

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800